{{- if not .Values.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psmdb-database.fullname" . }}
  labels:
{{ include "psmdb-database.labels" . | indent 4 }}
type: Opaque
data:
{{ .Values.users | toYaml | indent 2 }}
{{- end -}}



