apiVersion: psmdb.percona.com/v1-6-0
kind: PerconaServerMongoDB
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"psmdb.percona.com/v1-6-0","kind":"PerconaServerMongoDB"}
  name: {{ include "psmdb-database.fullname" . }}
  labels:
{{ include "psmdb-database.labels" . | indent 4 }}
spec:
  pause: {{ .Values.pause }}
  {{- if .Values.platform }}
  platform: {{ .Values.platform }}
  {{- end }}
  {{- if .Values.DNSsuffix }}
  clusterServiceDNSSuffix: {{ .Values.DNSsuffix }}
  {{- end }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: Always
  {{- if .Values.allowUnsafeConfigurations }}
  allowUnsafeConfigurations: true
  {{- end }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
{{ .Values.imagePullSecrets | toYaml | indent 4 }}
  {{- end }}
  {{- if .Values.runUid }}
  runUid: {{ .Values.runUid }}
  {{- end }}
  {{- if .Values.secrets }}
  secrets:
  {{ .Values.secrets | toYaml | indent 4 }}
  {{- else }}
  secrets:
    users: {{ include "psmdb-database.fullname" . }}-secrets
  {{- end }}
  {{- if .Values.updateStrategy }}
  updateStrategy: {{ .Values.updateStrategy }}
  upgradeOptions:
    versionServiceEndpoint: {{ .Values.upgradeOptions.versionServiceEndpoint }}
    apply: {{ .Values.upgradeOptions.apply }}
    schedule: {{ .Values.upgradeOptions.schedule }}
  {{- end }}
  pmm:
    enabled: {{ .Values.pmm.enabled }}
    image: "{{ .Values.pmm.image.repository }}:{{ .Values.pmm.image.tag }}"
    serverHost: {{ .Values.pmm.serverHost }}
  replsets:
  - name: {{ .Values.replset.name }}
    size: {{ .Values.replset.size }}
    affinity:
      antiAffinityTopologyKey: {{ .Values.replset.antiAffinityTopologyKey }}
    {{- if .Values.replset.priorityClass }}
    priorityClassName: {{ .Values.replset.priorityClass }}
    {{- end }}
    {{- if .Values.replset.annotations }}
    annotations:
{{ .Values.replset.annotations | toYaml | indent 6 }}
    {{- end }}
    {{- if .Values.replset.labels }}
    labels:
{{ .Values.replset.labels | toYaml | indent 6 }}
    {{- end }}
    {{- if .Values.replset.nodeSelector }}
    nodeSelector:
{{ .Values.replset.nodeSelector | toYaml | indent 6 }}
    {{- end }}
    {{- if .Values.replset.livenessProbe }}
    livenessProbe:
{{ .Values.replset.livenessProbe | toYaml | indent 6 }}
    {{- end }}
    podDisruptionBudget:
      {{- if .Values.replset.podDisruptionBudget.maxUnavailable }}
      maxUnavailable: {{ .Values.replset.podDisruptionBudget.maxUnavailable }}
      {{- else }}
      minAvailable: {{ .Values.replset.podDisruptionBudget.minAvailable }}
      {{- end }}
    expose:
      enabled: {{ .Values.replset.expose.enabled }}
      exposeType: {{ .Values.replset.expose.loadBalancer }}
    arbiter:
      enabled: {{ .Values.replset.arbiter.enabled }}
      size: {{ .Values.replset.arbiter.size }}
      affinity:
        antiAffinityTopologyKey: {{ .Values.replset.arbiter.antiAffinityTopologyKey }}
      {{- if .Values.replset.arbiter.priorityClass }}
      priorityClassName: {{ .Values.replset.arbiter.priorityClass }}
      {{- end }}
      {{- if .Values.replset.arbiter.annotations }}
      annotations:
{{ .Values.replset.arbiter.annotations | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.replset.arbiter.labels }}
      labels:
{{ .Values.replset.arbiter.labels | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.replset.arbiter.nodeSelector }}
      nodeSelector:
{{ .Values.replset.arbiter.nodeSelector | toYaml | indent 8 }}
      {{- end }}
    {{- if .Values.replset.schedulerName }}
    schedulerName: {{ .Values.replset.schedulerName }}
    {{- end }}
    resources:
{{ .Values.replset.resources | toYaml | indent 6 }}
    volumeSpec:
      {{- if .Values.replset.volumeSpec.hostPath }}
      hostPath:
        path: {{ .Values.replset.volumeSpec.hostPath }}
        type: Directory
      {{- else if .Values.replset.volumeSpec.pvc }}
      persistentVolumeClaim:
{{ .Values.replset.volumeSpec.pvc | toYaml | indent 8 }}
      {{- else }}
      emptyDir: {}
      {{- end }}

  sharding:
    enabled: {{ .Values.sharding.enabled }}

    configsvrReplSet:
      size: {{ .Values.sharding.configrs.size }}
      affinity:
        antiAffinityTopologyKey: {{ .Values.sharding.configrs.antiAffinityTopologyKey }}
      {{- if .Values.sharding.configrs.priorityClass }}
      priorityClassName: {{ .Values.sharding.configrs.priorityClass }}
      {{- end }}
      {{- if .Values.sharding.configrs.annotations }}
      annotations:
{{ .Values.sharding.configrs.annotations | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.sharding.configrs.labels }}
      labels:
{{ .Values.sharding.configrs.labels | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.sharding.configrs.nodeSelector }}
      nodeSelector:
{{ .Values.sharding.configrs.nodeSelector | toYaml | indent 8 }}
    {{- end }}
      podDisruptionBudget:
        {{- if .Values.sharding.configrs.podDisruptionBudget.maxUnavailable }}
        maxUnavailable: {{ .Values.sharding.configrs.podDisruptionBudget.maxUnavailable }}
        {{- else }}
        minAvailable: {{ .Values.sharding.configrs.podDisruptionBudget.minAvailable }}
        {{- end }}
      resources:
        limits:
          cpu: {{ .Values.sharding.configrs.resources.limits.cpu }}
          memory: {{ .Values.sharding.configrs.resources.limits.memory }}
        requests:
          cpu: {{ .Values.sharding.configrs.resources.requests.cpu }}
          memory: {{ .Values.sharding.configrs.resources.requests.memory }}
      volumeSpec:
        {{- if .Values.sharding.configrs.volumeSpec.hostPath }}
        hostPath:
          path: {{ .Values.sharding.configrs.volumeSpec.hostPath }}
          type: Directory
        {{- else if .Values.sharding.configrs.volumeSpec.pvc }}
        persistentVolumeClaim:
{{ .Values.sharding.configrs.volumeSpec.pvc | toYaml | indent 10 }}
        {{- else }}
        emptyDir: {}
        {{- end }}

    mongos:
      size: {{ .Values.sharding.mongos.size }}
      affinity:
        antiAffinityTopologyKey: {{ .Values.sharding.mongos.antiAffinityTopologyKey }}
      {{- if .Values.sharding.mongos.priorityClass }}
      priorityClassName: {{ .Values.sharding.mongos.priorityClass }}
      {{- end }}
      {{- if .Values.sharding.mongos.annotations }}
      annotations:
{{ .Values.sharding.mongos.annotations | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.sharding.mongos.labels }}
      labels:
{{ .Values.sharding.mongos.labels | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.sharding.mongos.nodeSelector }}
      nodeSelector:
{{ .Values.sharding.mongos.nodeSelector | toYaml | indent 8 }}
      {{- end }}
      podDisruptionBudget:
        {{- if .Values.sharding.mongos.podDisruptionBudget.maxUnavailable }}
        maxUnavailable: {{ .Values.sharding.mongos.podDisruptionBudget.maxUnavailable }}
        {{- else }}
        minAvailable: {{ .Values.sharding.mongos.podDisruptionBudget.minAvailable }}
        {{- end }}
      resources:
        limits:
          cpu: {{ .Values.sharding.mongos.resources.limits.cpu }}
          memory: {{ .Values.sharding.mongos.resources.limits.memory }}
        requests:
          cpu: {{ .Values.sharding.mongos.resources.requests.cpu }}
          memory: {{ .Values.sharding.mongos.resources.requests.memory }}
      expose:
        exposeType: {{ .Values.sharding.mongos.expose.exposeType }}
      {{- if .Values.sharding.mongos.loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
{{ .Values.sharding.mongos.loadBalancerSourceRanges | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.sharding.mongos.serviceAnnotations }}
      serviceAnnotations:
{{ .Values.sharding.mongos.serviceAnnotations | toYaml | indent 8 }}
      {{- end }}
      {{- if .Values.sharding.mongos.auditLog }}
      auditLog:
{{ .Values.sharding.mongos.auditLog | toYaml | indent 8 }}
      {{- end }}

  mongod:
    net:
      port: 27017
      hostPort: 0
    security:
      redactClientLogData: false
      enableEncryption: true
      encryptionKeySecret: {{ include "psmdb-database.fullname" . }}-mongodb-encryption-key
      encryptionCipherMode: AES256-CBC
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      wiredTiger:
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 100

  backup:
    enabled: {{ .Values.backup.enabled }}
    restartOnFailure: true
    image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
    serviceAccountName: percona-server-mongodb-operator
    {{- if .Values.backup.resources }}
    resources:
    {{ .Values.backup.resources | toYaml | indent 6 }}
    {{- end }}
    storages:
{{ .Values.backup.storages | toYaml | indent 6 }}
    tasks:
{{ .Values.backup.tasks | toYaml | indent 6 }}
