apiVersion: v2
name: pg-db
description: 'A Helm chart for Deploying the Percona PostgreSQL database by Percona Distribution for PostgreSQL Operator'
type: application
version: 2.2.1
appVersion: 2.2.0
home: https://docs.percona.com/percona-operator-for-postgresql/2.0/
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
  - name: nmarukovich
    email: natalia.marukovich@gmail.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
