apiVersion: v2
name: pg-db
description: 'A Helm chart for Deploying the Percona PostgreSQL database by Percona Distribution for PostgreSQL Operator'
type: application
version: 2.2.0
appVersion: 2.2.0
home: https://github.com/percona/percona-postgresql-operator
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
