apiVersion: v2
name: pmm
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 0.1.1
appVersion: "2.28.0"
home: https://github.com/percona/pmm
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: denisok
    email: denys.kondratenko@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://www.percona.com/sites/default/files/pmm-logo.png
