apiVersion: v2
name: pmm
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 0.3.4
appVersion: "2.29.1"
home: https://github.com/percona/pmm
maintainers:
  - name: nikita-b
    email: nikita.beletskii@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: denisok
    email: denys.kondratenko@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://www.percona.com/sites/default/files/pmm-logo.png
