{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pmm.fullname" . }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "apiextensions.k8s.io", "apps", "rbac.authorization.k8s.io"] # "" indicates the core API group
  resources:
  - namespaces
  - endpoints
  - services
  - nodes
  - pods
  - secrets
  - serviceaccounts
  - customresourcedefinitions
  - deployments
  - roles
  - rolebindings
  verbs:
  - get
  - watch
  - create
  - list
  - patch
  - delete
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
