{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  PMM_ADMIN_PASSWORD: {{ .Values.secret.pmm_password | default (randAscii 16) | b64enc | quote }}
  {{- if .Values.secret.oauth_client_id -}}
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ .Values.secret.oauth_client_id }}
  {{- end }}
  {{- if .Values.secret.oauth_client_secret -}}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.secret.oauth_client_secret }}
  {{- end }}
{{- end }}
