{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  PMM_ADMIN_PASSWORD: {{ .Values.secret.password | default (randAscii 16) | b64enc | quote }}
{{- end }}
