{{- $serviceType := .Values.service.type -}}
{{- if .Values.ingress.enabled -}}
{{- $serviceType = "ClusterIP" -}}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.service.finalizers }}
  finalizers:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ $serviceType }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "pmm.selectorLabels" . | nindent 4 }}
