apiVersion: v2
name: pg-operator
description: 'A Helm chart to deploy the v2beta version of Percona Operator for PostgreSQL.'
type: application
version: 2.2.0
appVersion: 2.2.0
home: https://docs.percona.com/percona-operator-for-postgresql/
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
